[package]
name = "ir-backend-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ir = { version = "0.1.0", path = "../ir" }
llvm-sys = "191.0.0"
