[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[dependencies]
color-format.workspace = true
dmap.workspace = true
tracing.workspace = true
segment-list.workspace = true
strum = { version = "0.26.3", features = ["derive"] }
