[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[dependencies]
color-format = { git = "https://github.com/LinusDikomey/color-format", version = "0.1.0" }
strum = { version = "0.26.3", features = ["derive"] }
dmap = { path = "../dmap" }
tracing.workspace = true
