#!/bin/bash

testing/run_examples | tee testing/output.txt
if [ "$(cat testing/expected_output.txt)" == "$(cat testing/output.txt)" ]; then
    echo "Tests OK"
else
    echo "Test failed. The outputs differ"
    delta testing/expected_output.txt testing/output.txt
fi
    