#!/bin/bash

testing/run_examples > testing/output.txt
if [ "$(cat testing/expected_output.txt)" == "$(cat testing/output.txt)" ]; then
    echo "Tests OK"
else
    echo "Test failed. The outputs differ"
    diff testing/expected_output.txt testing/output.txt
fi
    