[package]
name = "eye"
version = "0.1.0"
edition = "2021"

[features]
default = [
  "llvm-backend",
  #"x86-backend"
]
llvm-backend = ["dep:ir-backend-llvm"]
x86-backend = ["dep:ir-backend-x86"]
lsp = ["dep:eye-lsp"]

[dependencies]
compiler = { path = "../compiler" }
color-format = { git = "https://github.com/LinusDikomey/color-format" }
clap = { version = "4.4.13", features = ["derive"] }
eye-lsp = { path = "../eye-lsp", optional = true }
ir2 = { path = "../ir2" }

# backends
ir-backend-llvm = { path = "../ir-backend-llvm", optional = true }
ir-backend-x86 = { path = "../ir-backend-x86", optional = true }
pathdiff = "0.2.1"
