[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
token.workspace = true
dmap.workspace = true
id.workspace = true
error.workspace = true
span.workspace = true
types.workspace = true
