[package]
name = "eye-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
home = "0.5.9"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
